<?php 
	header('Content-type:text/cache-mainfest');
	header('Cache-Control:no-cache,must-revalidate');
	header('Pragma: no-cache');
	header('Expires: Mon, 26 Jul 1970 05:00:00 GMT');
?>
CACHE MANIFEST
#2018-08-24 10:36:44

CACHE:
appoint.html
appoint_detail.html
bg.png
cashier.html
cashier_detail.html
cashier_set.html
cashier_success.html
commodity.html
couponList.html
css/dropload.css
css/mobiscroll.2.13.2.css
css/mobiscroll_min.css
css/order_detail.css
css/pigcms.css
foodshop.html
foodshop_all.html
foodshop_cancel.html
foodshop_eat.html
foodshop_list.html
foodshop_menu.html
foodshop_order.html
foodshop_order_list.html
foodshop_reserve.html
foodshop_row_list.html
foodshop_table_list.html
group_detail.html
group_list.html
guadan.html
images/1wzf_07.png
images/2ddzt_03.png
images/budui.png
images/c.png
images/cany1.png
images/cany2.png
images/cany3.png
images/cashier_appoint.png
images/cashier_buy.png
images/cashier_buy_s.png
images/cashier_code.png
images/cashier_create.png
images/cashier_food.png
images/cashier_group.png
images/cashier_pay.png
images/cashier_pay_s.png
images/cashier_printer.png
images/cashier_scan.png
images/cashier_setting.png
images/cashier_shop.png
images/cg_03.jpg
images/che_03.png
images/che_04.png
images/cjcgt_03.png
images/cjcgt_07.png
images/cjcgt_10.png
images/compare.png
images/coupon.png
images/coupon_big.png
images/dct_03.png
images/ddtu_03.png
images/dd_03.png
images/dibt_03.png
images/dlbj_03.jpg
images/dl_07.png
images/dl_10.png
images/dui.png
images/dzt1.png
images/dzt2.png
images/dzt3.png
images/ewm_03.jpg
images/fht_03.png
images/fht_06.png
images/freeMoney.png
images/fuwut_03.png
images/fuwut_06.png
images/gdt_03.png
images/g_03.png
images/g_05.png
images/g_07.png
images/g_09.png
images/hht_07.jpg
images/hht_12.jpg
images/hsj_20.png
images/hykt_03.png
images/hykt_07.png
images/index_03.png
images/index_05.png
images/index_10.png
images/index_11.png
images/index_16.png
images/index_17.png
images/index_21.png
images/index_22.png
images/jinz_03.jpg
images/jsddt_03.png
images/jsddt_06.png
images/jsddt_10.png
images/jsddt_12.png
images/jsddt_14.png
images/jsdd_03.png
images/kd-img1.png
images/kd-img2.png
images/kd-img3.png
images/kd-img4.png
images/kd_03.png
images/kd_07.png
images/kd_11.png
images/ljt.png
images/loading.gif
images/logo.png
images/lt_03.png
images/map/deliver_pos.png
images/map/my_pos.png
images/map/road.png
images/map/store_pos.png
images/md_03.png
images/md_06.png
images/more_03.png
images/n.png
images/not_03.jpg
images/ph_03.png
images/ph_13.png
images/ph_16.png
images/ph_21.png
images/ph_25.png
images/ph_28.png
images/qh.png
images/qkt.jpg
images/ren_03.png
images/rt_03.png
images/scan.png
images/scan_again.png
images/scan_express.png
images/shanc_03.png
images/shop1.png
images/shopBoss.png
images/sst_06.png
images/sub_card.png
images/sxt.png
images/sxt_03.png
images/taika.png
images/tbty.png
images/tb_06.png
images/tb_10.png
images/tb_13.png
images/tb_17.png
images/tc.png
images/tcbj_06.jpg
images/tct_03.jpg
images/tct_04.jpg
images/tct_05.jpg
images/tct_06.jpg
images/tc_03.png
images/tht_11.png
images/time.png
images/time_07.png
images/tst_03.png
images/tst_07.png
images/tst_10.png
images/t_03.jpg
images/user_avatar.jpg
images/white_600.png
images/wxsm.jpg
images/wxsmt.png
images/x.png
images/xtb_03.png
images/xtb_06.png
images/xtb_08.png
images/xtb_14.png
images/xtb_16.png
images/xtb_20.png
images/xtb_22.png
images/xx_06.png
images/x_03.png
images/x_033.png
images/yhjdt_06.png
images/yhjy_03.png
images/yhjy_131_02.png
images/yh_10.png
images/yyddt_03.png
images/zftp_03.png
images/zftp_04.png
images/zftp_07.png
images/zftp_11.png
index.html
login.html
logo.png
reservation.html
reservation_detail.html
retail.html
scripts/common.js
scripts/dropload.js
scripts/fastclick.js
scripts/iscroll.js
scripts/jquery-1.8.3.min.js
scripts/jroll-infinite.js
scripts/JRoll.js
scripts/layer/layer.m.js
scripts/layer/need/layer.css
scripts/mobiscroll.2.13.2.js
scripts/swiper-3.3.1.jquery.min.js
scripts/work/appoint_order_detail.js
scripts/work/appoint_order_list.js
scripts/work/cashier.js
scripts/work/cashier_set.js
scripts/work/cashier_success.js
scripts/work/commodity.js
scripts/work/couponList.js
scripts/work/foodshop.js
scripts/work/foodshop_create.js
scripts/work/foodshop_menu.js
scripts/work/foodshop_order_list.js
scripts/work/foodshop_row_list.js
scripts/work/foodshop_table_list.js
scripts/work/group_detail.js
scripts/work/group_list.js
scripts/work/guadan.js
scripts/work/index.js
scripts/work/login.js
scripts/work/retail.js
scripts/work/setting.js
scripts/work/settlement.js
scripts/work/shop_goods_statistics.js
scripts/work/shop_order_detail.js
scripts/work/shop_order_list.js
scripts/work/shop_order_log.js
scripts/work/store.js
scripts/work/store_detail.js
scripts/work/store_qrcode.js
scripts/work/sub_card_order_detail.js
scripts/work/sub_card_order_list.js
setting.html
settlement.html
shop.html
shop_detail.html
shop_details.html
shop_order.html
shop_order_log.html
source/new_order.mp3
statistics.html
store.html
store_detail.html
store_qrcode.html
sub_card_order_detail.html
sub_card_order_list.html
sub_card_order_list1.html

NETWORK:
*