<?php 
	header('Content-type:text/cache-mainfest');
	header('Cache-Control:no-cache,must-revalidate');
	header('Pragma: no-cache');
	header('Expires: Mon, 26 Jul 1970 05:00:00 GMT');
?>
CACHE MANIFEST
#2018-08-20 13:15:56

CACHE:
bg.png
css/deliver.css
css/lCalendar.css
css/reply.css
detail.html
finish.html
grab.html
images/4-_10.png
images/4-_15.png
images/4-_24.png
images/48-1_03.png
images/7-6_03.png
images/7-6_07.png
images/7-6_09.png
images/dibut_05.png
images/dibut_05on.png
images/dibut_06.png
images/dibut_06on.png
images/dibut_07.png
images/dibut_07on.png
images/dindxqt_11.png
images/dindxqt_20.png
images/dindxqt_24.png
images/dindxqt_27.png
images/dizi.png
images/dlymt_04.png
images/dlymt_06.png
images/dlymt_11.png
images/f1.png
images/full_star.png
images/hq_07.jpg
images/login_02.jpg
images/map_center.png
images/my_03.png
images/my_14.png
images/my_17.png
images/none_star.png
images/nybjt_03.jpg
images/qdht_02.jpg
images/qdl_02.jpg
images/qdz_02.jpg
images/sj.png
images/tix_07.png
images/tjt_03.png
images/tjt_07.png
images/tjt_10.png
images/tjt_14.png
images/tjt_17.png
images/tjt_22.png
images/tjt_25.png
images/tjt_26.png
images/tjxhx_03.jpg
index.html
info.html
login.html
logo.png
new_order.mp3
pick.html
reply.html
scripts/common.js
scripts/fastclick.js
scripts/iscroll.js
scripts/jquery-1.8.3.min.js
scripts/jroll-infinite.js
scripts/JRoll.js
scripts/layer/layer.m.js
scripts/layer/need/layer.css
scripts/lCalendar.js
scripts/swiper-3.3.1.jquery.min.js
scripts/work/common.js
scripts/work/detail.js
scripts/work/finish.js
scripts/work/grab.js
scripts/work/index.js
scripts/work/info.js
scripts/work/login.js
scripts/work/pick.js
scripts/work/reply.js
scripts/work/setting.js
scripts/work/tongji.js
setting.html
tongji.html

NETWORK:
*